# Generated by Django 4.1 on 2022-10-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timesince',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
