# Generated by Django 4.1 on 2022-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_frequentlyaskedquestion_pertanyaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='pertanyaan',
            field=models.TextField(),
        ),
    ]
