# Generated by Django 4.1 on 2022-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_frequentlyaskedquestion_pertanyaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='user',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
