# Generated by Django 4.1 on 2022-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_frequentlyaskedquestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='jawaban',
            field=models.TextField(blank=True, default='Belum ada jawaban', null=True),
        ),
    ]
