# Generated by Django 4.1 on 2022-10-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentikasi', '0002_rename_userprofile_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
