# Generated by Django 4.1 on 2022-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_bio_alter_userprofile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saldo',
            field=models.BigIntegerField(default=0),
        ),
    ]
