# Generated by Django 4.1 on 2022-10-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_birthday_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='homepage/static/img/person.png', null=True, upload_to='userprofile/images'),
        ),
    ]
