# Generated by Django 4.1 on 2022-11-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='homepage/static/img/person.png', upload_to='media'),
        ),
    ]
