# Generated by Django 4.1 on 2022-12-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
