# Generated by Django 4.1 on 2022-10-26 08:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crowdfund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('collected', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('target', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)])),
                ('deadline', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 26, 15, 57, 41, 982611))])),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)])),
                ('comment', models.CharField(max_length=1000)),
                ('crowdfund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.crowdfund')),
            ],
        ),
    ]
