# Generated by Django 4.1 on 2022-10-26 09:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='collected',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crowdfund',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 26, 16, 15, 42, 895371))]),
        ),
    ]
