# Generated by Django 4.1 on 2022-10-26 09:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0002_alter_crowdfund_collected_alter_crowdfund_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 26, 9, 26, 50, 509823, tzinfo=datetime.timezone.utc))]),
        ),
    ]
