# Generated by Django 4.1 on 2022-10-26 23:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0003_alter_crowdfund_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 26, 23, 39, 43, 18853, tzinfo=datetime.timezone.utc))]),
        ),
    ]
