# Generated by Django 4.1 on 2022-10-27 12:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0004_alter_crowdfund_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 27, 12, 32, 9, 793084, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
