# Generated by Django 4.1 on 2022-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0005_alter_crowdfund_deadline_alter_donation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crowdfund',
            name='target',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
