# Generated by Django 4.1 on 2022-10-29 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_saldo'),
        ('crowdfund', '0006_alter_crowdfund_deadline_alter_crowdfund_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfund',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='crowdfund',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
