# Generated by Django 4.1 on 2022-10-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0007_crowdfund_fundraiser_donation_donator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfund',
            name='fundraiser_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donator_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
